### ISSUE TITLE
I am getting a error while connection to the WebSocket 

### ISSUE THREAD

**Issue by halfstackpgr** [HazemMeqdad/lavaplayer#35]
```
E 2022-12-30 22:39:49,289 asyncio: Task exception was never retrieved
future: <Task finished name='Task-23' coro=<WS._connect() done, defined at C:\Users\halfs\AppData\Roaming\Python\Python39\site-packages\lavaplayer\websocket.py:52> exception=AttributeError("'NoneType' object has no attribute 'closed'")>
Traceback (most recent call last):
  File "C:\Users\halfs\AppData\Roaming\Python\Python39\site-packages\lavaplayer\websocket.py", line 77, in _connect
    await self.send({
  File "C:\Users\halfs\AppData\Roaming\Python\Python39\site-packages\lavaplayer\websocket.py", line 180, in send
    if not self.is_connected:
  File "C:\Users\halfs\AppData\Roaming\Python\Python39\site-packages\lavaplayer\websocket.py", line 177, in is_connected
    return self.is_connect and self.ws.closed is False
AttributeError: 'NoneType' object has no attribute 'closed'

```
Is this even an error or just randomly spawned crash output ?

**Comment by HazemMeqdad** [comment]
Sure the ip server is available.

**Comment by HazemMeqdad** [comment]
Sure if this values is correct
![image](https://user-images.githubusercontent.com/66125469/210173479-9e22722e-247a-4524-afec-b10cf8e9f352.png)

**Comment by chredeur0** [comment]
> Sure if this values is correct ![image](https://user-images.githubusercontent.com/66125469/210173479-9e22722e-247a-4524-afec-b10cf8e9f352.png)

Personally I am not sure 🤔
